### ISSUE TITLE
Código

### ISSUE THREAD

**Issue by rodineicirineu** [meninobirno/BotAliexpress#1]
Quais as instruções para utilização?

**Comment by meninobirno** [comment]
Opa meu mano, perdão pela demora para te responder. Então cara, é bem simplão, primeiro tu precisa ter a versão 77 do chrome, depois tu coloca a url do teu carrinho de compras ali na url, põe um breakpoint no método validaUrl no program e inicia o projeto. Logo após iniciar, ele vai abrir uma página do chrome e o teu código vai parar ali no breakpoint, você faz o login na janela que abriu e logo depois é só continuar a depuração
